# Generated by Django 2.2.12 on 2025-03-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='saitama-season-3-3840x2160-21513.jpg.', upload_to=''),
        ),
    ]
